### ISSUE TITLE
Grundprogramm Passwortgenerator

### ISSUE THREAD

**Issue by Lakyrea** [archanyhm/DevelsAdvocate#13]
Am Ende soll es möglich sein, Passwörter zu generieren

**Comment by archanyhm** [comment]
Wichtig: Es sollte sichergestellt werden, dass kein einfacher PRNG-Algorithmus genutzt wird, um die Zufallspasswörter zu generieren. Es sollte auf eine Alternative zurückgegriffen werden, die entsprechend viel Entropie stellt
