### ISSUE TITLE
Grundprogramm Zahlenkonverter

### ISSUE THREAD

**Issue by Lakyrea** [archanyhm/DevelsAdvocate#14]
Dezimal <-> Binär mit Bibliothek

**Comment by archanyhm** [comment]
Ist in dem Fall tatsächlich eine Biblothek notwendig? Bitte begründen

**Comment by DerKevos** [comment]
![image](https://user-images.githubusercontent.com/90282032/155515198-5129d025-8bb9-42ca-8dc1-0831a24494f3.png)

Hilfestellung

**Comment by DerKevos** [comment]
Mathematischen Ansatz geschaffen.
Modulo Ansatz.
Code erweitert.
To-do: Listen in C# ansehen und implementieren (Arrays Rückwerts darstellen).
