### ISSUE TITLE
Unit Tests für Zahlenkonverter-Grundkonstrukt

### ISSUE THREAD

**Issue by Lakyrea** [archanyhm/DevelsAdvocate#16]

**Comment by DerKevos** [comment]
![image](https://user-images.githubusercontent.com/90282032/155501009-3d877042-8aa5-4971-aaa0-52e1608f6292.png)

Feststellung: 2 Arten von Binär Zahlen (Mathematisch und Maschinen Darstellung 
Im Rahmen dieser Issues werden wir nur den mathematischen Ansatz bearbeiten. 
Maschinen Darstellung wird in einer anderen Issue bearbeitet ( https://github.com/archanyhm/DevelsAdvocate/issues/49 ) 
Farben: Rot: Must-have
             Gelb: Should-have
             Grün: Could-have
